module.exports= {
    profiles: [
        {
            first_name: "Vikram",
            last_name: "Vedachalam",
            designation: "Database Admin",
            location: "New York",
            work_authorization: "H1B",
            time_zone: "America/Chicago",
            employment_type: "Permanent",
            experience: "8years",
            education: "Bachelor in technology",
            salary: "10000",
            company_name: "Accenture",
            willing_to_relocate: true,
            language: "English",
            security_clearance: "Military",
            notice_period: "immediately",
            last_updated: "7 Days Ago",
            last_viewed: "7 Days Ago",
            portal: "Internaldb",
            skills: ["sql", "sqlserver"]
        },
        {
            first_name: "Arun",
            last_name: "Shesha",
            designation: "Devops Engineer",
            location: "New York",
            work_authorization: "H1B",
            time_zone: "America/New_York",
            employment_type: "Permanent",
            experience: "8years",
            education: "Bachelor in technology",
            salary: "10000",
            company_name: "Accenture",
            willing_to_relocate: true,
            language: "English",
            security_clearance: "Military",
            notice_period: "immediately",
            last_updated: "7 Days Ago",
            last_viewed: "7 Days Ago",
            portal: "Internaldb",
            skills: ["devops", "linux"]
        },
        {
            first_name: "Johnny",
            last_name: "Vedachal",
            designation: "Database Admin",
            location: "New York",
            work_authorization: "H1B",
            time_zone: "America/New_York",
            employment_type: "Permanent",
            experience: "8years",
            education: "Bachelor in technology",
            salary: "10000",
            company_name: "Accenture",
            willing_to_relocate: true,
            language: "English",
            security_clearance: "Military",
            notice_period: "immediately",
            last_updated: "7 Days Ago",
            last_viewed: "7 Days Ago",
            portal: "Internaldb",
            skills: ["sql", "sqlserver"]
        },
        {
            first_name: "Vel",
            last_name: "Ram",
            designation: "Software Developer",
            location: "New York",
            work_authorization: "H1B",
            time_zone: "America/New_York",
            employment_type: "Permanent",
            experience: "8years",
            education: "Bachelor in technology",
            salary: "10000",
            company_name: "accenture",
            willing_to_relocate: true,
            language: "english",
            security_clearance: "military",
            notice_period: "immediately",
            last_updated: "7 Days Ago",
            last_viewed: "7 Days Ago",
            portal: "Monster",
            skills: ["java", "eclipse"]
        },
        {
            first_name: "Iliyas",
            last_name: "Mohammed",
            designation: "Nodejs Developer",
            location: "Los Angeles",
            work_authorization: "H1B",
            time_zone: "America/New_York",
            employment_type: "Permanent",
            experience: "5years",
            education: "Bachelor in technology",
            salary: "100000",
            company_name: "accenture",
            willing_to_relocate: true,
            language: "english",
            security_clearance: "military",
            notice_period: "immediately",
            last_updated: "7 Days Ago",
            last_viewed: "7 Days Ago",
            portal: "Dice",
            skills: ["nodejs", "expressjs"]
        },
        {
            first_name: "Sreepal",
            last_name: "Sree",
            designation: "Angularjs Developer",
            location: "Los Angeles",
            work_authorization: "H1B",
            time_zone: "America/New_York",
            employment_type: "Permanent",
            experience: "5years",
            education: "Bachelor in technology",
            salary: "100000",
            company_name: "TCS",
            willing_to_relocate: true,
            language: "english",
            security_clearance: "military",
            notice_period: "immediately",
            last_updated: "7 Days Ago",
            last_viewed: "7 Days Ago",
            portal: "Dice",
            skills: ["angularjs", "reactjs"]
        },
        {
            first_name: "Meganathan",
            last_name: "Sekhar",
            designation: "Angularjs Developer",
            location: "New York",
            work_authorization: "H1B",
            time_zone: "America/New_York",
            employment_type: "Permanent",
            experience: "5years",
            education: "Bachelor in technology",
            salary: "100000",
            company_name: "TCS",
            willing_to_relocate: true,
            language: "english",
            security_clearance: "military",
            notice_period: "immediately",
            last_updated: "7 Days Ago",
            last_viewed: "7 Days Ago",
            portal: "Dice",
            skills: ["angularjs", "reactjs"]
        },
        {
            first_name: "Ragav",
            last_name: "Sekhar",
            designation: "Python Developer",
            location: "New York",
            work_authorization: "H1B",
            time_zone: "America/New_York",
            employment_type: "Permanent",
            experience: "5years",
            education: "Bachelor in technology",
            salary: "100000",
            company_name: "TCS",
            willing_to_relocate: true,
            language: "english",
            security_clearance: "military",
            notice_period: "immediately",
            last_updated: "7 Days Ago",
            last_viewed: "7 Days Ago",
            portal: "Dice",
            skills: ["python", "reactjs"]
        },
        {
            first_name: "Vengatesh",
            last_name: "s",
            designation: "Full Stack Developer",
            location: "New York",
            work_authorization: "H1B",
            time_zone: "America/New_York",
            employment_type: "Permanent",
            experience: "5years",
            education: "Bachelor in technology",
            salary: "100000",
            company_name: "TCS",
            willing_to_relocate: true,
            language: "english",
            security_clearance: "military",
            notice_period: "immediately",
            last_updated: "7 Days Ago",
            last_viewed: "7 Days Ago",
            portal: "Dice",
            skills: ["reactjs", "nodejs"]
        },
        {
            first_name: "Vengatesh",
            last_name: "s",
            designation: "Full Stack Developer",
            location: "New York",
            work_authorization: "H1B",
            time_zone: "America/New_York",
            employment_type: "Permanent",
            experience: "5years",
            education: "Bachelor in technology",
            salary: "100000",
            company_name: "TCS",
            willing_to_relocate: true,
            language: "english",
            security_clearance: "military",
            notice_period: "immediately",
            last_updated: "7 Days Ago",
            last_viewed: "7 Days Ago",
            portal: "Dice",
            skills: ["reactjs", "nodejs"]
        }
    ]
}